#!/bin/bash
#======================================================================================
# Disable bogus crash reports on startup
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 01-Feb-2014
# Author: Dave Nicolette
#======================================================================================

pushd /etc/default
sudo cp apport apport-orig
sudo sed 's/.*enabled=1*/enabled=0/' apport-orig > apport
popd
