#!/bin/bash
#======================================================================================
# Install Ruby and friends
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 12 Aug 2014
# Author: Dave Nicolette
#======================================================================================

echo
echo '============================================================='
echo 'Installing Ruby...'

pushd "$HOME"
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1
echo 'source "$HOME/.rvm/scripts/rvm"' >> .bashrc
. .bashrc
rvm --default use 2.1.1
gem install bundler
popd

if [[ -z ~/bin ]]; then
	pushd ~
    mkdir -p bin
    echo "export PATH=~/bin:$PATH" >> .bashrc
    . .bashrc
    popd
    cp fixrvm "$HOME/bin"
    chmod +x "$HOME/bin/fixrvm"
fi    
