#!/bin/bash
#======================================================================================
# Install MongoDB
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 28-Apr-2014
# Author: Dave Nicolette
#======================================================================================

echo
echo '============================================================='
echo 'Installing MongoDB...'

sudo apt-get -y -f install mongodb

