#!/bin/bash
#======================================================================================
# Install OpenJDK 7
#
# Arguments:
# (None)		
#
# Version: 1.1.0
# Date: 14 Aug 2014
# Author: Dave Nicolette
#======================================================================================
sudo apt-get install -y -f openjdk-7-jdk
