#!/bin/bash
#======================================================================================
# Install Oracle Java 8
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 14 Aug 2014
# Author: Dave Nicolette
#======================================================================================
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get -y update
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get -y -f install oracle-java8-installer
sudo apt-get -y -f install oracle-java8-set-default
sudo update-java-alternatives -s java-8-oracle
