#!/bin/bash
#======================================================================================
# Install Maven3
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 11 Sep 2014
# Author: Dave Nicolette
#======================================================================================

echo
echo '============================================================='
echo 'Installing Maven...'

sudo add-apt-repository "deb http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main"
sudo apt-get update
sudo apt-get -y -f install maven3
sudo ln -s /usr/share/maven3/bin/mvn /usr/bin/mvn
