#!/bin/bash
#======================================================================================
# Install Tomcat 7.
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 11 Sep 2014
# Author: Dave Nicolette
#======================================================================================
echo
echo '============================================================='
echo 'Installing Tomcat 7...'

sudo apt-get -y -f tomcat7 \
    tomcat7-docs \
    tomcat7-admin \
    tomcat7-examples

sudo echo 'JAVA_HOME=/usr/lib/jvm/java-8-oracle' >> /etc/default/tomcat7

sudo cp tomcat-users.xml /etc/tomcat7/tomcat-users.xml
sudo chmod 640 /etc/tomcat7/tomcat-users.xml

sudo /etc/init.d/tomcat7 restart

